Super/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings

from product.views import HomeView
from cart.views import CartListView

from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from dajaxice.core import dajaxice_autodiscover, dajaxice_config
dajaxice_autodiscover()

urlpatterns = [
    #url(dajaxice_config.dajaxice_url, include('dajaxice.urls')),

    url(r'^$', HomeView.as_view(), name='home'),  

    url(r'^admin/', include(admin.site.urls)),

	url(r'^product/', include("product.urls")),
    url(r'^account/', include("account.urls")),
    url(r'^cart/', include("cart.urls")),
    url(r'^order/', include("order.urls")),



]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += staticfiles_urlpatterns()

cart/urls.py
from django.conf.urls import include, url, patterns
from .views import CartListView, ajaxAddToCart
urlpatterns = patterns(
	"",
    url(r'^$', CartListView.as_view(),name="cart"),
    url(r'^ajax/addToCart/$', ajaxAddToCart),
 	   
)

product/urls.py
from django.conf.urls import include, url, patterns
from .views import ProductListView,ProductDetailView, ajaxCommentForm
urlpatterns = patterns(
	"",
    url(r'^$', ProductListView.as_view(),name="product"),

    url(r'^(?P<pk>\d+)/$', ProductDetailView.as_view()),

    url(r'^(?P<slug>\w+)/$', ProductDetailView.as_view()),
    url(r'^ajax/comment/$', ajaxCommentForm),
 	   
)

comments/models.py
from django.db import models
from account.models import Account
from product.models import Product
from django.db.models import Sum, Avg

RATING_CHOICE = [(0,0),(1,1),(2,2),(3,3),(4,4),(5,5)]

# Create your models here.
class Comments(models.Model):
	user = models.ForeignKey(Account)
	product = models.ForeignKey(Product)


	comments = models.TextField(max_length=200, null=True, blank=True)
	rating = models.IntegerField(choices=RATING_CHOICE, default=0)

	created_date = models.DateTimeField(auto_now_add=True)
	modified_date = models.DateTimeField(auto_now=True)

	@staticmethod
	def average_rating(self):
		all_comments = Comments.objects.filter(rating__gte =0)
		avg_rating = all_comments.aggregate(Avg('rating'))
		return avg_rating['rating__avg']

	def __str__(self):
		return "%s  > %s > %s" %(self.user, self.product, self.comments)

product/models.py
from django.db import models
from django.contrib.auth.models import User
from mptt.models import MPTTModel, TreeForeignKey
# Create your models here.


DISTRICT_CHOICE=[('KTM','Kathmandu'),
	('LAL','Lalitpur'),
	('BKT','Bhaktapur')
	]

class Location(models.Model):
	district = models.CharField(choices=DISTRICT_CHOICE, max_length=50)
	village = models.CharField(max_length=100)
	ward_no = models.CharField(max_length=100)
	slug = models.SlugField(unique=True)


	def __str__(self):
		return "%s %s %s" %(self.district, self.village, self.ward_no)


class Category(MPTTModel):
	name = models.CharField(max_length=200)
	slug = models.SlugField(unique=True)
	parent = TreeForeignKey('self', null=True, blank=True, related_name='children', db_index=True)

class MPTTMeta:
    	order_insertion_by = ['name']

def __str__(self):
        return self.name

class Product(models.Model):
	name = models.CharField(max_length=255, blank=False, null=False)
	slug = models.SlugField(unique=True)
	description = models.TextField()
	price = models.DecimalField(decimal_places=2, max_digits=11)
	qty = models.IntegerField()
	#photo = models.ImageField(upload_to='product',blank=True, null=True)

	
	location = models.ForeignKey(Location)
	manufacturer = models.ForeignKey(User)
	category = TreeForeignKey('Category', null=True, blank=True, db_index=True)


	def get_averageRating(self):
		from comments.models import Comments
		avg_rating = Comments.average_rating(self)
		return avg_rating


	def get_manufacturer_email(self):
		return self.manufacturer.email
	get_manufacturer_email.short_description='Email'#change the header in the table

	def __str__(self):
		return self.name

class ProductImage(models.Model):
    photo = models.ImageField(upload_to='Product_images',blank = True, null = True)
    obj = models.ForeignKey(Product)

    

product/views.py
import json
from django.shortcuts import render
from django.http import HttpResponse
from django.views.generic import ListView, TemplateView
from django.views.generic.detail import DetailView
from django.views.decorators.csrf import csrf_exempt


from .models import Product, Category
from comments.models import Comments
# Create your views here.
class ProductListView(ListView):
	model=Product
	#template_name='base.html'
	

class ProductDetailView(DetailView):
	model=Product
	#template_name='base.html'
	def get_context_data(self, **kwargs):
		context = super(ProductDetailView, self).get_context_data(**kwargs)
		context['category_list'] = Category.objects.all()#filter(parent__isnull=True)
		
		return context

class HomeView(TemplateView):
	template_name='product/home.html'
	model = ProductDetailView
	def get_context_data(self, **kwargs):
		context = super(HomeView, self).get_context_data(**kwargs)
		context['product_list'] = Product.objects.filter()[:2]
		#context['featured_items'] = Product.objects.all()[:2]
		return context

@csrf_exempt
def ajaxCommentForm(request):
	if(request.method == 'POST'):
		comment = Comments(
			user_id = request.user.id,
			product_id = request.POST['product_id'],
			comments = request.POST['comment'],
			rating = request.POST['rating']
			)
		comment.save()
		response_data = {}
		mydata = {
				'comment_id':comment.id,
				'time':comment.created_date.strftime("%H - %M %P"),
				'date':comment.created_date.strftime("%Y / %b / %d"),
				'comment_user':comment.user.user.username,
				'comment_text':comment.comments,
				'rating': comment.rating
				}
		response_data['result'] = 'Sucess'
		response_data['data'] = mydata

		return HttpResponse(json.dumps(response_data), content_type='application/json')

templates/product/product_detail.html
{% extends 'base.html' %}
{% load staticfiles %} 
{% load product_category %}
{% load thumbnail%}
{% block content %}
	<div class="col-sm-9 padding-right">
		<div class="product-details"><!--product-details-->
			<div class="col-sm-5">
				<div class="view-product">
				{% thumbnail object.productimage_set.all.0.photo '300' as im %}
									<img src='{{ im.url }}' class="girl img-responsive" alt=""/>
					{% endthumbnail%}
					<h3></h3>
				</div>
				<div id="similar-product" class="carousel slide" data-ride="carousel">
					
					  <!-- Wrapper for slides -->
					    <div class="carousel-inner">
							<div class="item active">
							  <a href=""><img src="images/product-details/similar1.jpg" alt=""></a>
							  <a href=""><img src="images/product-details/similar2.jpg" alt=""></a>
							  <a href=""><img src="images/product-details/similar3.jpg" alt=""></a>
							</div>
							<div class="item">
							  <a href=""><img src="images/product-details/similar1.jpg" alt=""></a>
							  <a href=""><img src="images/product-details/similar2.jpg" alt=""></a>
							  <a href=""><img src="images/product-details/similar3.jpg" alt=""></a>
							</div>
							<div class="item">
							  <a href=""><img src="images/product-details/similar1.jpg" alt=""></a>
							  <a href=""><img src="images/product-details/similar2.jpg" alt=""></a>
							  <a href=""><img src="images/product-details/similar3.jpg" alt=""></a>
							</div>
							
						</div>

					  <!-- Controls -->
					  <a class="left item-control" href="#similar-product" data-slide="prev">
						<i class="fa fa-angle-left"></i>
					  </a>
					  <a class="right item-control" href="#similar-product" data-slide="next">
						<i class="fa fa-angle-right"></i>
					  </a>
				</div>

			</div>
			<div class="col-sm-7">
				<div class="product-information"><!--/product-information-->
					<h2>{{ object.name }}</h2>
					<p>Web ID: {{object.id}}</p>
					<p>Rating: {{ object.get_averageRating }}</p>
					<img src="{% static 'images/product-details/rating.png' %}" alt="" />
					<span>
						<span>Rs. {{object.price}}</span>
						<label>Quantity:</label>

						<div class="cart_quantity_button">
									
									<input class="cart_quantity_input" id="productQuantity" type="number" name="quantity" value="1" autocomplete="off" size="2" {%if object.qty == 0 %}disabled="disabled"{% endif %}>
									
						</div>


						<button type="button" class="btn btn-fefault cart">
							<i class="fa fa-shopping-cart"></i>
							Add to cart
						</button>
					</span>
					<p><b>Availability:</b>{%if object.qty == 0 %}Out of Stock{% else %} In Stock {% endif %}</p>
					<p><b>Condition:</b> New</p>
					<p><b>Brand:</b> E-SHOPPER</p>
					<a href=""><img src="{% static 'images/product-details/share.png' %}" class="share img-responsive"  alt="" /></a>
				</div><!--/product-information-->
			</div>
		</div><!--/product-details-->
		
		<div class="category-tab shop-details-tab"><!--category-tab-->
			<div class="col-sm-12">
				<ul class="nav nav-tabs">
					<li class="active"><a href="#details" data-toggle="tab">Details</a></li>
					<!-- <li><a href="#companyprofile" data-toggle="tab">Company Profile</a></li>
					<li><a href="#tag" data-toggle="tab">Tag</a></li> -->
					<li><a href="#reviews" data-toggle="tab">Reviews ({{object.comments_set.all.count}})</a></li>
				</ul>
			</div>
			<div class="tab-content">
				<div class="tab-pane fade in active" id="details" >
					{{object.description}}
				</div>
				
				<div class="tab-pane fade" id="companyprofile" >
					<div class="col-sm-3">
						<div class="product-image-wrapper">
							<div class="single-products">
								<div class="productinfo text-center">
									<img src="images/home/gallery1.jpg" alt="" />
									<h2>$56</h2>
									<p>Easy Polo Black Edition</p>
									<button type="button" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</button>
								</div>
							</div>
						</div>
					</div>
					<div class="col-sm-3">
						<div class="product-image-wrapper">
							<div class="single-products">
								<div class="productinfo text-center">
									<img src="images/home/gallery3.jpg" alt="" />
									<h2>$56</h2>
									<p>Easy Polo Black Edition</p>
									<button type="button" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</button>
								</div>
							</div>
						</div>
					</div>
					<div class="col-sm-3">
						<div class="product-image-wrapper">
							<div class="single-products">
								<div class="productinfo text-center">
									<img src="images/home/gallery2.jpg" alt="" />
									<h2>$56</h2>
									<p>Easy Polo Black Edition</p>
									<button type="button" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</button>
								</div>
							</div>
						</div>
					</div>
					<div class="col-sm-3">
						<div class="product-image-wrapper">
							<div class="single-products">
								<div class="productinfo text-center">
									<img src="images/home/gallery4.jpg" alt="" />
									<h2>$56</h2>
									<p>Easy Polo Black Edition</p>
									<button type="button" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</button>
								</div>
							</div>
						</div>
					</div>
				</div>
				
				<div class="tab-pane fade" id="tag" >
					<div class="col-sm-3">
						<div class="product-image-wrapper">
							<div class="single-products">
								<div class="productinfo text-center">
									<img src="images/home/gallery1.jpg" alt="" />
									<h2>$56</h2>
									<p>Easy Polo Black Edition</p>
									<button type="button" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</button>
								</div>
							</div>
						</div>
					</div>
					<div class="col-sm-3">
						<div class="product-image-wrapper">
							<div class="single-products">
								<div class="productinfo text-center">
									<img src="images/home/gallery2.jpg" alt="" />
									<h2>$56</h2>
									<p>Easy Polo Black Edition</p>
									<button type="button" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</button>
								</div>
							</div>
						</div>
					</div>
					<div class="col-sm-3">
						<div class="product-image-wrapper">
							<div class="single-products">
								<div class="productinfo text-center">
									<img src="images/home/gallery3.jpg" alt="" />
									<h2>$56</h2>
									<p>Easy Polo Black Edition</p>
									<button type="button" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</button>
								</div>
							</div>
						</div>
					</div>
					<div class="col-sm-3">
						<div class="product-image-wrapper">
							<div class="single-products">
								<div class="productinfo text-center">
									<img src="images/home/gallery4.jpg" alt="" />
									<h2>$56</h2>
									<p>Easy Polo Black Edition</p>
									<button type="button" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</button>
								</div>
							</div>
						</div>
					</div>
				</div>
				
				<div class="tab-pane fade" id="reviews" >
					<div class="col-sm-12">
						<div  id="commentList">
						{% for comment in object.comments_set.all %}
							<ul>
								<li><a href=""><i class="fa fa-user"></i>{{ comment.user.user }}</a></li>
								<li><a href=""><i class="fa fa-clock-o"></i>{{ comment.created_date|date:"h:i A" }}</a></li>
								<li><a href=""><i class="fa fa-calendar-o"></i>{{ comment.created_date|date:"d M Y" }}</a></li>
							</ul>
							<p style="background-color: #f5f5f5; padding: 5px; margin-bottom:20px;">{{comment.comments}}</p>
						{% endfor %}
						</div>

						<p><b>Write Your Review</b></p>
						
						<form action="#">
							<textarea name="" id="comment"></textarea>
							<b>Rating: </b> <input id="rating" type='number'><img src="images/product-details/rating.png" alt="" />
							<button type="button" class="btn btn-default pull-right comment_form_submit">
								Submit
							</button>
						</form>
					</div>
				</div>
				
			</div>
		</div><!--/category-tab-->
		
		
	</div>
{% endblock %}
{% block left_sidebar %}

	{% show_category category_list %}

{% endblock%}

{% block recommended %}
	{% include 'recommended.html' %}
{% endblock %}

{% block javascript %}
	<script>
	$.fn.appendComment=function (obj){
		var comment = '<ul>\
							<li><a href=""><i class="fa fa-user"></i>'+ obj.data.comment_user+'</a></li>\
							<li><a href=""><i class="fa fa-clock-o"></i>'+ obj.data.time+'</a></li>\
							<li><a href=""><i class="fa fa-calendar-o"></i>'+ obj.data.date+'</a></li>\
						</ul>\
						<p style="background-color: #f5f5f5; padding: 5px; margin-bottom:20px;">'+obj.data.comment_text+'</p>';
		$(this).append(comment);

	}
	
	$('.comment_form_submit').click(function(){
		var comment = $('#comment').val().trim();
		var rating = $('#rating').val().trim();
		if(comment == '') return false;
		var data ={'comment':comment, 'product_id':{{object.id}},'rating':rating };

		//console.log(data);
		$.ajax({
			type: "POST",
			url: '/product/ajax/comment/',
			data: data, 
			success: successFun,

		});
		function successFun(data){
			console.log(data);
			$('#commentList').appendComment(data);
		}
	})

	$('.cart').click(function(){
		alert('123');
		var quantity = $('#productQuantity').val();
		if(quantity == '') return false;
		var data ={'quantity':quantity, 'product_id':{{object.id}} };

		//console.log(data);
		$.ajax({
			type: "POST",
			url: '/cart/ajax/addToCart/',
			data: data, 
			success: successFun,

		});
		function successFun(data){
			alert(data.result);
			// $('#commentList').appendComment(data);
		}
	})
</script>
{% endblock%}

templates/product/product_list.html
{% extends 'base.html'%}

{% load staticfiles %}
{% block content %}	
<div class="col-sm-12 padding-left">
					<div class="features_items"><!--features_items-->
						<h2 class="title text-center">Features Items</h2>
						
						
						{%for product in product_list %}
						
						<div class="col-sm-4">
							<div class="product-image-wrapper">
								<div class="single-products">
									<a href="{{ product.slug }}">
										<div class="productinfo text-center">
											<img src="/media/{{ product.productimage_set.all.0.photo }}" alt="" />
											<h2><span>Rs. </span>{{product.price}}</h2>
											<p>{{product.name}}</p>
											<a href="{{ product.slug }}" class="btn btn-default add-to-cart"><i class="fa fa-info"></i>Details</a>
										</div>
										</a>
									
								</div>
								<div class="choose">
									<ul class="nav nav-pills nav-justified">
										<li><a href=""><i class="fa fa-plus-square"></i>Add to wishlist</a></li>
										<li><a href=""><i class="fa fa-plus-square"></i>Add to compare</a></li>
									</ul>
								</div>
							</div>
						</div>

						{% endfor %}
						
						
						
						<ul class="pagination">
							<li class="active"><a href="">1</a></li>
							<li><a href="">2</a></li>
							<li><a href="">3</a></li>
							<li><a href="">&raquo;</a></li>
						</ul>
					</div><!--features_items-->
				</div>
{% endblock %}
{% block left_sidebar %}{% endblock %}

{% block recommended %}{% endblock %}