Super/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings

from product.views import HomeView
from cart.views import CartListView

from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from dajaxice.core import dajaxice_autodiscover, dajaxice_config
dajaxice_autodiscover()

urlpatterns = [
    #url(dajaxice_config.dajaxice_url, include('dajaxice.urls')),

    url(r'^$', HomeView.as_view(), name='home'),  

    url(r'^admin/', include(admin.site.urls)),

	url(r'^product/', include("product.urls")),
    url(r'^account/', include("account.urls")),
    url(r'^cart/', include("cart.urls")),
    url(r'^order/', include("order.urls")),



]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += staticfiles_urlpatterns()

cart/urls.py
from django.conf.urls import include, url, patterns
from .views import CartListView, ajaxAddToCart
urlpatterns = patterns(
	"",
    url(r'^$', CartListView.as_view(),name="cart"),
    url(r'^ajax/addToCart/$', ajaxAddToCart),
 	   
)

cart/models.py
from django.db import models
from django.contrib.auth.models import User
from product.models import Product

# Create your models here.


class Cart(models.Model):
	user = models.ForeignKey(User)
	product = models.ForeignKey(Product)
	quantity = models.IntegerField(default=0)

	created_date = models.DateTimeField(auto_now_add=True)
	modified_date = models.DateTimeField(auto_now=True)

	def __str__(self):
		return "%s  > %s > %s" %(self.user, self.product, self.quantity)

product/models.py
from django.db import models
from django.contrib.auth.models import User
from mptt.models import MPTTModel, TreeForeignKey
# Create your models here.


DISTRICT_CHOICE=[('KTM','Kathmandu'),
	('LAL','Lalitpur'),
	('BKT','Bhaktapur')
	]

class Location(models.Model):
	district = models.CharField(choices=DISTRICT_CHOICE, max_length=50)
	village = models.CharField(max_length=100)
	ward_no = models.CharField(max_length=100)
	slug = models.SlugField(unique=True)


	def __str__(self):
		return "%s %s %s" %(self.district, self.village, self.ward_no)


class Category(MPTTModel):
	name = models.CharField(max_length=200)
	slug = models.SlugField(unique=True)
	parent = TreeForeignKey('self', null=True, blank=True, related_name='children', db_index=True)

class MPTTMeta:
    	order_insertion_by = ['name']

def __str__(self):
        return self.name

class Product(models.Model):
	name = models.CharField(max_length=255, blank=False, null=False)
	slug = models.SlugField(unique=True)
	description = models.TextField()
	price = models.DecimalField(decimal_places=2, max_digits=11)
	qty = models.IntegerField()
	#photo = models.ImageField(upload_to='product',blank=True, null=True)

	
	location = models.ForeignKey(Location)
	manufacturer = models.ForeignKey(User)
	category = TreeForeignKey('Category', null=True, blank=True, db_index=True)


	def get_averageRating(self):
		from comments.models import Comments
		avg_rating = Comments.average_rating(self)
		return avg_rating


	def get_manufacturer_email(self):
		return self.manufacturer.email
	get_manufacturer_email.short_description='Email'#change the header in the table

	def __str__(self):
		return self.name

class ProductImage(models.Model):
    photo = models.ImageField(upload_to='Product_images',blank = True, null = True)
    obj = models.ForeignKey(Product)

    

cart/views.py
from django.shortcuts import render
from django.views.generic import ListView
from .models import Cart
from product.models import Product
from django.views.decorators.csrf import csrf_exempt
from django.http import HttpResponse
import json

# Create your views here.


class CartListView(ListView):

	model = Cart
	template_name = "cart.html"
	def get_queryset(self):
 		return Cart.objects.filter(user = self.request.user)

				


@csrf_exempt
def ajaxAddToCart(request):
	if(request.method == 'POST'):
		print request.POST
		cart, isCreated = Cart.objects.get_or_create(user = request.user, product_id = request.POST['product_id'])
	
		if isCreated:
			cart.quantity = request.POST['quantity']
		else:
			cart.quantity = cart.quantity + int(request.POST['quantity'])

		cart.save()



		response_data = {}
		data = {
				'cart':cart.id
				}
		response_data['result'] = 'Sucess'
		response_data['data'] = data

		return HttpResponse(json.dumps(response_data), content_type='application/json')

templates/base.html
<!DOCTYPE html>
{%load staticfiles%}
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>{{object.name}} | E-Shopper</title>
   	<link href="{% static 'css/bootstrap.min.css'%}" rel="stylesheet">
    <link href="{% static 'css/font-awesome.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/prettyPhoto.css' %}" rel="stylesheet">
    <link href="{% static 'css/price-range.css' %}" rel="stylesheet">
    <link href="{% static 'css/animate.css' %}" rel="stylesheet">
	<link href="{% static 'css/main.css' %}" rel="stylesheet">
	<link href="{% static 'css/responsive.css' %}" rel="stylesheet">
	<link href="{% static 'css/custom.css' %}" rel="stylesheet">

    <!--[if lt IE 9]>
    <script src="js/html5shiv.js"></script>
    <script src="js/respond.min.js"></script>
    <![endif]-->       
    <link rel="shortcut icon" href="{% static 'images/ico/favicon.ico' %}">
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="{% static 'images/ico/apple-touch-icon-144-precomposed.png' %}">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="{% static 'images/ico/apple-touch-icon-114-precomposed.png' %}">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="{% static 'images/ico/apple-touch-icon-72-precomposed.png">
    <link rel="apple-touch-icon-precomposed" href="{% static 'images/ico/apple-touch-icon-57-precomposed.png' %}">
</head><!--/head-->

<body>
	{% block header %}
		{%include 'header.html' %}
	{% endblock %}
{% block advertisement %}
{% endblock %}
	<section>
		<div class="container">
			<div class="row">
				{% block left_sidebar %}
					
				{% endblock %}

				{% block content%}
				<div class="col-sm-9 padding-right"></div>
				{% endblock %}
				
				
				</div>
				{% block recommended %}
				
				{% endblock %}
			</div>
		</div>
	</section>
	
	{% block footer %}
		{% include 'footer.html' %}
	{% endblock %}
	

  
    <script src="{% static 'js/jquery.js' %}"></script>
	<script src="{% static 'js/price-range.js' %}"></script>
    <script src="{% static 'js/jquery.scrollUp.min.js' %}"></script>
	<script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/jquery.prettyPhoto.js' %}"></script>
    <script src="{% static 'js/main.js'%}"></script>
    {% block javascript %}

    {% endblock javascript %}

</body>
</body>
</html>

templates/cart.html
{% extends 'base.html'%}
{% block content%}
	
	
	
	
		<section id="cart_items">
		<div class="container">
			<div class="breadcrumbs">
				<ol class="breadcrumb">
				  <li><a href="#">Home</a></li>
				  <li class="active">Shopping Cart</li>
				</ol>
			</div>
			<div class="table-responsive cart_info">
				<table class="table table-condensed">
					<thead>
						<tr class="cart_menu">
							<td class="image">Item</td>
							<td class="description"></td>
							<td class="price">Price</td>
							<td class="quantity">Quantity</td>
							<td class="total">Total</td>
							<td></td>
						</tr>
					</thead>
					<tbody>
						
					{% for product in cart_list %}
						<tr>
							<td class="cart_product">
								<a href=""><img  height="100" src="/media/{{product.product.productimage_set.all.0.photo}}" alt=""></a>
							</td>
							<td class="cart_description">
								<h4><a href="">{{product.product.description}}</a></h4>
								<p>Web ID: {{product.product.id}}</p>
							</td>
							<td class="cart_price">
								<p>{{product.product.price}}</p>
							</td>
							<td class="cart_quantity">
								<div class="cart_quantity_button">
									<button class="cart_quantity_up" id="{{ product.id }}"> + </button>
									<input class="cart_quantity_input" type="text" name="quantity" value="{{ product.quantity }}" autocomplete="off" size="2">
									<button class="cart_quantity_down" id="{{product.id}}"> - </button>
								</div>
							</td>
							<td class="cart_total">
								<p class="cart_total_price">{{ product.product.price }}</p>
							</td>
							<td class="cart_delete">
								<a class="cart_quantity_delete" href=""><i class="fa fa-times"></i></a>
							</td>
						</tr>
					{% endfor %}
					
					</tbody>
				</table>
			</div>
		</div>
	</section> <!--/#cart_items-->

	<section id="do_action">
		<div class="container">
			<div class="heading">
				<h3>What would you like to do next?</h3>
				<p>Choose if you have a discount code or reward points you want to use or would like to estimate your delivery cost.</p>
			</div>
			<div class="row">
				<div class="col-sm-6">
					<div class="chose_area">
						<ul class="user_option">
							<li>
								<input type="checkbox">
								<label>Use Coupon Code</label>
							</li>
							<li>
								<input type="checkbox">
								<label>Use Gift Voucher</label>
							</li>
							<li>
								<input type="checkbox">
								<label>Estimate Shipping & Taxes</label>
							</li>
						</ul>
						<ul class="user_info">
							<li class="single_field">
								<label>Country:</label>
								<select>
									<option>United States</option>
									<option>Bangladesh</option>
									<option>UK</option>
									<option>India</option>
									<option>Pakistan</option>
									<option>Ucrane</option>
									<option>Canada</option>
									<option>Dubai</option>
								</select>
								
							</li>
							<li class="single_field">
								<label>Region / State:</label>
								<select>
									<option>Select</option>
									<option>Dhaka</option>
									<option>London</option>
									<option>Dillih</option>
									<option>Lahore</option>
									<option>Alaska</option>
									<option>Canada</option>
									<option>Dubai</option>
								</select>
							
							</li>
							<li class="single_field zip-field">
								<label>Zip Code:</label>
								<input type="text">
							</li>
						</ul>
						<a class="btn btn-default update" href="">Get Quotes</a>
						<a class="btn btn-default check_out" href="">Continue</a>
					</div>
				</div>
				<div class="col-sm-6">
					<div class="total_area">
						<ul>
							<li>Cart Sub Total <span>$59</span></li>
							<li>Eco Tax <span>$2</span></li>
							<li>Shipping Cost <span>Free</span></li>
							<li>Total <span>$61</span></li>
						</ul>
							<a class="btn btn-default update" href="">Update</a>
							<a class="btn btn-default check_out" href="">Check Out</a>
					</div>
				</div>
			</div>
		</div>
	</section><!--/#do_action-->
{% endblock %}

templates/checkout.html
{% extends 'base.html' %}
{% block content %}
	<section id="cart_items">
		<div class="container">
			<div class="breadcrumbs">
				<ol class="breadcrumb">
				  <li><a href="#">Home</a></li>
				  <li class="active">Check out</li>
				</ol>
			</div><!--/breadcrums-->
 
			<div class="step-one">
				<h2 class="heading">Step 1</h2>
			</div>
			<div class="checkout-options">
				{% if request.user.is_authenticated %}
					<h3>{{ request.user.username }}</h3>
					<div class="register-req">
					<p>You are Registered User Please proceed to next Step</p>
				</div>
				{% else %}		
					<ul class="nav">
						<li>
							<label><a href="{% url 'account_signup' %}"> Register Account</a></label>
						</li>
					</ul>
					<div class="register-req">
					<p>Please use Register And Checkout to easily get access to your order history, or use Checkout as Guest</p>
				</div>
{% endif%}

			</div><!--/checkout-options-->

			<!--/register-req-->

			<div class="shopper-informations">
				<div class="row">
					<div class="col-sm-3">
						<div class="shopper-info">
							<p>Shopper Information</p>
							<form>
								<input type="text" value="{{request.user.username}}" readonly="true">
								<input type="text" value="{{request.user.firstname}}" readonly="true">
							</form>
						</div>
					</div>
					<div class="col-sm-5 clearfix">
						<div class="bill-to">
							<p>Bill To</p>
							<div class="form-one">
								<form>
									<input type="text" placeholder="Company Name">
									<input type="text" placeholder="Email*">
									<input type="text" placeholder="Title">
									<input type="text" placeholder="First Name *">
									<input type="text" placeholder="Middle Name">
									<input type="text" placeholder="Last Name *">
									<input type="text" placeholder="Address 1 *">
									<input type="text" placeholder="Address 2">
								</form>
							</div>
							<div class="form-two">
								<form>
									<input type="text" placeholder="Zip / Postal Code *">
									<select>
										<option>-- Country --</option>
										<option>United States</option>
										<option>Bangladesh</option>
										<option>UK</option>
										<option>India</option>
										<option>Pakistan</option>
										<option>Ucrane</option>
										<option>Canada</option>
										<option>Dubai</option>
									</select>
									<select>
										<option>-- State / Province / Region --</option>
										<option>United States</option>
										<option>Bangladesh</option>
										<option>UK</option>
										<option>India</option>
										<option>Pakistan</option>
										<option>Ucrane</option>
										<option>Canada</option>
										<option>Dubai</option>
									</select>
									<input type="password" placeholder="Confirm password">
									<input type="text" placeholder="Phone *">
									<input type="text" placeholder="Mobile Phone">
									<input type="text" placeholder="Fax">
								</form>
							</div>
						</div>
					</div>
					<div class="col-sm-4">
						<div class="order-message">
							<p>Shipping Order</p>
							<textarea name="message"  placeholder="Notes about your order, Special Notes for Delivery" rows="16"></textarea>
							<label><input type="checkbox"> Shipping to bill address</label>
						</div>	
					</div>					
				</div>
			</div>
			<div class="review-payment">
				<h2>Review & Payment</h2>
			</div>

		<div class="table-responsive cart_info">
				<table class="table table-condensed">
					<thead>
						<tr class="cart_menu">
							<td class="image">Item</td>
							<td class="description"></td>
							<td class="price">Price</td>
							<td class="quantity">Quantity</td>
							<td class="total">Total</td>
							<td></td>
						</tr>
					</thead>
					<tbody>
						
					{% for product in cart_list %}
						<tr>
							<td class="cart_product">
								<a href=""><img  height="100" src="/media/{{product.product.productimage_set.all.0.photo}}" alt=""></a>
							</td>
							<td class="cart_description">
								<h4><a href="">{{product.product.description}}</a></h4>
								<p>Web ID: {{product.product.id}}</p>
							</td>
							<td class="cart_price">
								<p>{{product.product.price}}</p>
							</td>
							<td class="cart_quantity">
								<div class="cart_quantity_button">
									<button class="cart_quantity_up" id="{{ product.id }}"> + </button>
									<input class="cart_quantity_input" type="text" name="quantity" value="{{ product.quantity }}" autocomplete="off" size="2">
									<button class="cart_quantity_down" id="{{product.id}}"> - </button>
								</div>
							</td>
							<td class="cart_total">
								<p class="cart_total_price">{{ product.product.price }}</p>
							</td>
							<td class="cart_delete">
								<a class="cart_quantity_delete" href=""><i class="fa fa-times"></i></a>
							</td>
						</tr>
					{% endfor %}
					
					</tbody>
				</table>
			</div>
			<div class="payment-options">
					<span>
						<label><input type="checkbox"> Direct Bank Transfer</label>
					</span>
					<span>
						<label><input type="checkbox"> Check Payment</label>
					</span>
					<span>
						<label><input type="checkbox"> Paypal</label>
					</span>
				</div>
		</div>
	</section> <!--/#cart_items-->

{% endblock%}

templates/footer.html
{% load staticfiles %}
<footer id="footer"><!--Footer-->
		<div class="footer-top">
			<div class="container">
				<div class="row">
					<div class="col-sm-2">
						<div class="companyinfo">
							<h2><span>e</span>-shopper</h2>
							<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit,sed do eiusmod tempor</p>
						</div>
					</div>
					<div class="col-sm-7">
						<div class="col-sm-3">
							<div class="video-gallery text-center">
								<a href="#">
									<div class="iframe-img">
										<img src="{% static 'images/home/iframe1.png'%}" alt="" />
									</div>
									<div class="overlay-icon">
										<i class="fa fa-play-circle-o"></i>
									</div>
								</a>
								<p>Circle of Hands</p>
								<h2>24 DEC 2014</h2>
							</div>
						</div>
						
						<div class="col-sm-3">
							<div class="video-gallery text-center">
								<a href="#">
									<div class="iframe-img">
										<img src="{% static 'images/home/iframe2.png'%}" alt="" />
									</div>
									<div class="overlay-icon">
										<i class="fa fa-play-circle-o"></i>
									</div>
								</a>
								<p>Circle of Hands</p>
								<h2>24 DEC 2014</h2>
							</div>
						</div>
						
						<div class="col-sm-3">
							<div class="video-gallery text-center">
								<a href="#">
									<div class="iframe-img">
										<img src="{% static 'images/home/iframe3.png'%}" alt="" />
									</div>
									<div class="overlay-icon">
										<i class="fa fa-play-circle-o"></i>
									</div>
								</a>
								<p>Circle of Hands</p>
								<h2>24 DEC 2014</h2>
							</div>
						</div>
						
						<div class="col-sm-3">
							<div class="video-gallery text-center">
								<a href="#">
									<div class="iframe-img">
										<img src="{% static 'images/home/iframe4.png'%}" alt="" />
									</div>
									<div class="overlay-icon">
										<i class="fa fa-play-circle-o"></i>
									</div>
								</a>
								<p>Circle of Hands</p>
								<h2>24 DEC 2014</h2>
							</div>
						</div>
					</div>
					<div class="col-sm-3">
						<div class="address">
							<img src="{% static 'images/home/map.png'%}" alt="" />
							<p>505 S Atlantic Ave Virginia Beach, VA(Virginia)</p>
						</div>
					</div>
				</div>
			</div>
		</div>
		
		<div class="footer-widget">
			<div class="container">
				<div class="row">
					<div class="col-sm-2">
						<div class="single-widget">
							<h2>Service</h2>
							<ul class="nav nav-pills nav-stacked">
								<li><a href="">Online Help</a></li>
								<li><a href="">Contact Us</a></li>
								<li><a href="">Order Status</a></li>
								<li><a href="">Change Location</a></li>
								<li><a href="">FAQ’s</a></li>
							</ul>
						</div>
					</div>
					<div class="col-sm-2">
						<div class="single-widget">
							<h2>Quock Shop</h2>
							<ul class="nav nav-pills nav-stacked">
								<li><a href="">T-Shirt</a></li>
								<li><a href="">Mens</a></li>
								<li><a href="">Womens</a></li>
								<li><a href="">Gift Cards</a></li>
								<li><a href="">Shoes</a></li>
							</ul>
						</div>
					</div>
					<div class="col-sm-2">
						<div class="single-widget">
							<h2>Policies</h2>
							<ul class="nav nav-pills nav-stacked">
								<li><a href="">Terms of Use</a></li>
								<li><a href="">Privecy Policy</a></li>
								<li><a href="">Refund Policy</a></li>
								<li><a href="">Billing System</a></li>
								<li><a href="">Ticket System</a></li>
							</ul>
						</div>
					</div>
					<div class="col-sm-2">
						<div class="single-widget">
							<h2>About Shopper</h2>
							<ul class="nav nav-pills nav-stacked">
								<li><a href="">Company Information</a></li>
								<li><a href="">Careers</a></li>
								<li><a href="">Store Location</a></li>
								<li><a href="">Affillate Program</a></li>
								<li><a href="">Copyright</a></li>
							</ul>
						</div>
					</div>
					<div class="col-sm-3 col-sm-offset-1">
						<div class="single-widget">
							<h2>About Shopper</h2>
							<form action="#" class="searchform">
								<input type="text" placeholder="Your email address" />
								<button type="submit" class="btn btn-default"><i class="fa fa-arrow-circle-o-right"></i></button>
								<p>Get the most recent updates from <br />our site and be updated your self...</p>
							</form>
						</div>
					</div>
					
				</div>
			</div>
		</div>
		
		<div class="footer-bottom">
			<div class="container">
				<div class="row">
					<p class="pull-left">Copyright © 2013 E-SHOPPER Inc. All rights reserved.</p>
					<p class="pull-right">Designed by <span><a target="_blank" href="http://www.themeum.com">Themeum</a></span></p>
				</div>
			</div>
		</div>
		
	</footer><!--/Footer-->

templates/header.html
{%load staticfiles%}
{% load i18n staticfiles %}

<header id="header"><!--header-->
		<div class="header_top"><!--header_top-->
			<div class="container">
				<div class="row">
					<div class="col-sm-6">
						<div class="contactinfo">
							<ul class="nav nav-pills">
								<li><a href=""><i class="fa fa-phone"></i> +2 95 01 88 821</a></li>
								<li><a href=""><i class="fa fa-envelope"></i> info@domain.com</a></li>
							</ul>
						</div>
					</div>
					<div class="col-sm-6">
						<div class="social-icons pull-right">
							<ul class="nav navbar-nav">
								<li><a href=""><i class="fa fa-facebook"></i></a></li>
								<li><a href=""><i class="fa fa-twitter"></i></a></li>
								<li><a href=""><i class="fa fa-linkedin"></i></a></li>
								<li><a href=""><i class="fa fa-dribbble"></i></a></li>
								<li><a href=""><i class="fa fa-google-plus"></i></a></li>
							</ul>
						</div>
					</div>
				</div>
			</div>
		</div><!--/header_top-->
		
		<div class="header-middle"><!--header-middle-->
			<div class="container">
				<div class="row">
					<div class="col-sm-4">
						<div class="logo pull-left">
							<a href="{% url 'home' %}"><img src="{% static 'images/home/logo.png' %}" alt="" /></a>
						</div>
						<div class="btn-group pull-right">
							<div class="btn-group">
								<button type="button" class="btn btn-default dropdown-toggle usa" data-toggle="dropdown">
									USA
									<span class="caret"></span>
								</button>
								<ul class="dropdown-menu">
									<li><a href="">Canada</a></li>
									<li><a href="">UK</a></li>
								</ul>
							</div>
							
							<div class="btn-group">
								<button type="button" class="btn btn-default dropdown-toggle usa" data-toggle="dropdown">
									DOLLAR
									<span class="caret"></span>
								</button>
								<ul class="dropdown-menu">
									<li><a href="">Canadian Dollar</a></li>
									<li><a href="">Pound</a></li>
								</ul>
							</div>
						</div>
					</div>
					<div class="col-sm-8">
						<div class="shop-menu pull-right">
							<ul class="nav navbar-nav">
							{% if request.user.is_authenticated %}
								<li><a href="{% url 'account_profile'%}"><i class="fa fa-user"></i>{% trans 'Hi' %}, {{request.user.username}}!</a></li>
								<li><a href=""><i class="fa fa-star"></i> Wishlist</a></li>
								<li><a href="checkout.html"><i class="fa fa-crosshairs"></i> Checkout</a></li>
								<li><a href="{% url 'cart' %}"><i class="fa fa-shopping-cart"></i> Cart</a></li>
								<li>
								<a href="{% url 'account_logout' %}"><i class="fa fa-sign-out"></i> Logout</a>
							{% else %}

								
								<li><a href=""><i class="fa fa-star"></i> Wishlist</a></li>
								<li><a href="checkout.html"><i class="fa fa-crosshairs"></i> Checkout</a></li>
								<li><a href="{% url 'account_login' %}"><i class="fa fa-shopping-cart"></i> Cart</a></li>
								<li>
								<a href="{% url 'account_login' %}"><i class="fa fa-lock"></i> Login</a>
								{% endif %}</li>
							</ul>
						</div>
					</div>
				</div>
			</div>
		</div><!--/header-middle-->
	
		<div class="header-bottom"><!--header-bottom-->
			<div class="container">
				<div class="row">
					<div class="col-sm-9">
						<div class="navbar-header">
							<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
								<span class="sr-only">Toggle navigation</span>
								<span class="icon-bar"></span>
								<span class="icon-bar"></span>
								<span class="icon-bar"></span>
							</button>
						</div>
						<div class="mainmenu pull-left">
							<ul class="nav navbar-nav collapse navbar-collapse">
								<li><a href="{% url 'home'%}" class="active">Home</a></li>
								<li class="dropdown"><a href="#">Shop<i class="fa fa-angle-down"></i></a>
                                    <ul role="menu" class="sub-menu">
                                        <li><a href="{% url 'product'%}">Products</a></li>
										<li><a href="checkout.html">Checkout</a></li> 
										<li><a href="cart.html">Cart</a></li> 
										<li><a href="login.html">Login</a></li> 
                                    </ul>
                                </li> 
								<li class="dropdown"><a href="#">Blog<i class="fa fa-angle-down"></i></a>
                                    <ul role="menu" class="sub-menu">
                                        <li><a href="blog.html">Blog List</a></li>
										<li><a href="blog-single.html">Blog Single</a></li>
                                    </ul>
                                </li> 
								<li><a href="404.html">404</a></li>
								<li><a href="contact-us.html">Contact</a></li>
							</ul>
						</div>
					</div>
					<div class="col-sm-3">
						<div class="search_box pull-right">
							<input type="text" placeholder="Search"/>
						</div>
					</div>
				</div>
			</div>
		</div><!--/header-bottom-->
	</header><!--/header-->
	